getDataValidtionForField = (field) ->
  ss = SpreadsheetApp.getActiveSpreadsheet()
  sheet = ss.getSheetByName('DataValidation')
  range = sheet.getRange(1, 1, 1, sheet.getLastColumn())
  dataValidationFields = range.getValues()[0]
  i = 0
  len = dataValidationFields.length
  while i < len
    dataValidationFieldName = dataValidationFields[i]
    if field == dataValidationFieldName
      dataValidationRange = sheet.getRange(2, i + 1, sheet.getLastRow())
      return SpreadsheetApp.newDataValidation().requireValueInRange(dataValidationRange).build()
    i++
  return

# ---
# generated by js2coffee 2.2.0